# Generated by Django 6.1.1 on 2026-10-05 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='url',
            field=models.URLField(max_length=2000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка'),
        ),
    ]
