# Generated by Django 6.1.1 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_alter_collectionitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (видно посетителям)'),
        ),
    ]
